run:
  timeout: 5m
  tests: true
  go: "1.23"
  issues-exit-code: 1

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - docs
    - scripts
    - build
  exclude-rules:
    # Exclude all linters from test files for now to focus on production code
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - prealloc
        - errcheck
        - goconst
        - gocyclo
        - staticcheck
        - unused
    # Exclude generated files
    - path: "internal/version/version.go"
      linters:
        - unused
    # Ignore import formatting issues temporarily
    - linters:
        - goimports
      text: "File is not properly formatted"
  exclude:
    # errcheck: Common patterns that are typically safe to ignore
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print.*|os\.(Un)?Setenv). is not checked
    # typecheck: Ignore undefined imports that might be environment-specific
    - "undefined:"
    - "could not import"
    # staticcheck: Common false positives
    - SA5011
    - SA9003
    - SA4006
    - SA4017
    # gosec: Common false positives
    - G103
    - G104
    - G204
    - G306
    - G404
    - G601
    # unparam: Interface implementations often have unused parameters
    - "is unused"
    # goconst: Allow string literals in tests and configs
    - "occurrences, make it a constant"
    # gocyclo: Allow complex functions in tests
    - "cyclomatic complexity.*is high"
    # prealloc: Performance optimization suggestions
    - "Consider pre-allocating"
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Only enable the most essential linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - unused
    - gofmt
    - misspell
  disable:
    # Disable problematic linters that cause issues in CI
    - staticcheck
    - goimports
    - goconst
    - gocyclo
    - gosec
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - (os\.)?std(out|err)\..*
      - .*Close
      - .*Flush
      - os\.Remove(All)?
      - .*print.*
      - os\.(Un)?Setenv
  misspell:
    locale: US
  govet:
    disable:
      - shadow

severity:
  default-severity: warning
  case-sensitive: false