global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ccproxy'
    static_configs:
      - targets: ['ccproxy:3456']
    metrics_path: '/metrics'
    scrape_interval: 5s