apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccproxy
  labels:
    app: ccproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ccproxy
  template:
    metadata:
      labels:
        app: ccproxy
    spec:
      containers:
      - name: ccproxy
        image: ghcr.io/yourusername/ccproxy:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3456
          protocol: TCP
        env:
        - name: CCPROXY_HOST
          value: "0.0.0.0"
        - name: CCPROXY_PORT
          value: "3456"
        - name: CCPROXY_API_KEY
          valueFrom:
            secretKeyRef:
              name: ccproxy-secrets
              key: api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ccproxy-secrets
              key: anthropic-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /home/ccproxy/.ccproxy/config.json
          subPath: config.json
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: ccproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: ccproxy
  labels:
    app: ccproxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: ccproxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccproxy-config
data:
  config.json: |
    {
      "host": "0.0.0.0",
      "port": 3456,
      "log": true,
      "providers": [],
      "routes": {
        "default": {
          "provider": "anthropic",
          "model": "claude-3-sonnet-20240229"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: ccproxy-secrets
type: Opaque
stringData:
  api-key: "your-ccproxy-api-key"
  anthropic-api-key: "your-anthropic-api-key"
  openai-api-key: "your-openai-api-key"