version: '3.8'

services:
  ccproxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7187:7187"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=7187
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - GROQ_BASE_URL=https://api.groq.com/openai/v1
      - GROQ_MODEL=moonshotai/kimi-k2-instruct
      - GROQ_MAX_TOKENS=16384
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7187/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ccproxy-network

networks:
  ccproxy-network:
    driver: bridge